config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'music_studio/index'

  get 'studios/index'

  resources :studios do
    resources :bookings
  end

  root 'music_studio#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :studio
  validates :start_time,:end_time, :presence => true

end

app/models/studio.rb
class Studio < ApplicationRecord
  has_many :bookings, dependent: :destroy
  belongs_to :users ,optional: true
  validates_uniqueness_of :name
  validates :name,:price,:opening_time,:closing_time,:location, :presence => true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookings, dependent: :destroy
  has_many :studios, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!

  def new
    @studio= Studio.find_by_id(params[:studio_id])
    @booking=current_user.bookings.build
  end
  def index
  end

  def create
    @studio= Studio.find_by_id(params[:studio_id])
    if params[:start_time].present? && params[:end_time].present?
      @booking=Booking.where("((end_time > ?) OR (start_time BETWEEN ? AND ?)) AND status= ? AND studio_id=?",DateTime.parse(params[:start_time]),DateTime.parse(params[:start_time]),DateTime.parse(params[:end_time]),"Confirmed",@studio.id)
      if ((@booking.present?) || (@studio.opening_time >DateTime.parse(params[:start_time]) || @studio.closing_time< DateTime.parse(params[:end_time]) ))
          flash[:notice]="Studio has already been booked for this time, Please select some other time slot."
          render :new
      else
        @studio= Studio.find_by_id(params[:studio_id])
        @booking=current_user.bookings.build(booking_params)
        @booking.studio_id=@studio.id
        @booking.status="Confirmed"
        if @booking.save!
          flash[:notice]="Successfuilly booked the studio."
          redirect_to music_studio_index_path
        end
      end
    end
  end


  private

  def booking_params
    params.permit(:start_time,:end_time)
  end
end

app/controllers/music_studio_controller.rb
 class MusicStudioController < ApplicationController
  before_action :check_value, only: [:index],if: -> {params[:start_time].present? && params[:end_time].present?}

  def index
    @studios=Studio.all.left_outer_joins(:bookings).distinct
    if params[:location].present?
      @studios=@studios.where('location like ?',"%#{params[:location]}%")
    end
    if params[:start_time].present? && params[:end_time].present?
      @studios = @studios.where('opening_time <= ? AND closing_time >= ? AND bookings.start_time BETWEEN ? AND ? AND bookings.start_time!= ? AND bookings.status !=? AND bookings.start_time!=?',Time.parse(params[:start_time]),Time.parse(params[:end_time]),Time.parse(params[:start_time]),Time.parse(params[:end_time]),"NULL","Confirmed","NULL")
    end
  end

  private

  def check_value
    if(params[:start_time] > params[:end_time] || params[:start_time] < Time.now)
      flash[:error] = "Select Appropriate Date Time."
      redirect_to  music_studio_index_path
    end
  end

end

app/controllers/studios_controller.rb
class StudiosController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @studio = Studio.find(params[:id])
  end

  def new
    @studio = current_user.studios.build
  end

  def create
    @studio=Studio.new(studio_params)
    @studio.user_id=current_user.id
    if @studio.save
      flash[:notice] = "Successfully created studio!"
      redirect_to studio_path(@studio)
    else
      flash[:alert] = "Error creating new studio!"
      render :new
    end
  end



  def show

  end

  private

  def studio_params
    params.require(:studio).permit(:name, :location, :opening_time, :closing_time, :studio_type, :price)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/music_studio_helper.rb
module MusicStudioHelper
end

app/helpers/studio_helper.rb
module StudioHelper
end

app/views/bookings/new.html.erb
<div class="container-fluid">
  <%= form_tag(studio_bookings_path) do %>
    <div class="row" id="start-id">
      <div class='col-sm-6'>
        <label for="start_time">*Start Time</label>
        <%= text_field_tag :start_time%>
      </div>
      <div class='col-sm-6'>
        <label for="end_time">*End Time</label>
        <%=text_field_tag :end_time%>
      </div>
    <br>
  </br>
    <div class="row" id="booking-id">
      <div class='col-sm-6'>
        <%= submit_tag "Create Booking"%>
      </div>
    </div>
  <%end%>
</div>

<style>
#start-id{
  margin-left: 50px;
}
#booking-id{
  margin-top: 100px;
  margin-left: 440px;
}
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Musicstudio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container-fluid">
      <div class="row header">
        <h2>MusicStudio</h2>
        <% if user_signed_in? %>
          <%= button_to "SignOut",destroy_user_session_path,class: 'btn btn-primary',method: :delete%>
        <%else%>
          <%= button_to "SignUp",new_user_registration_path,class: 'btn btn-primary', id: 'signup-id' ,method: :get%>
          <%= button_to "SignIn",new_user_session_path,class: 'btn btn-primary', id: 'signin-id'%>
        <%end%>
        <%= button_to "Post a new MusicStudio",new_studio_path, class:"btn btn-primary",method: :get %>
      </div>
      </br>
      </br>
      <%= yield %>
    </div>
  </body>
</html>

app/views/music_studio/index.html.erb
<div class="container-fluid">
  <div class="row">
    <%= form_tag(music_studio_index_path, method: :get) do %>
      <div class='col-sm-3'>
        <div class="input-group">
          <label for="location" class= "location-data">Location</label>
          <%= text_field_tag :location,nil, placeholder: 'Enter Location Here..'%>
        </div>
      </div>
      <div class='col-sm-3'>
        <div class="input-group">
          <label for="start_time" class="start_time-data">Start Time</label>
          <%= text_field_tag :start_time,nil, placeholder: 'Enter Start Time Here..'%>
        </div>
      </div>
      <div class='col-sm-3'>
        <div class="input-group">
          <label for="end_time" class="end_time-data">End Time</label>
          <%=text_field_tag :end_time,nil, placeholder: 'Enter End Time Here..'%>
        </div>
      </div>
      <div class='col-sm-3'>
        <div class="input-group">
          <%= submit_tag "Search"%>
        </div>
      </div>
    <%end%>
    </div>
  </div>
<hr>

  <div class="row3">
    <%@studios.each do |studio|%>
      <div class="text-center">
        <h3><%= link_to "#{studio.name}",{controller: "studios", action: "index",id: studio.id},method: :get%></h3>
        <div>
          <%=studio.location%>
        </div>
        <p>Rs. <%=studio.price%></p>
        <hr>
      </div>
    <%end%>
  </div>
</div>



<style>
h2{
  display: inline-block;
  position: relative;
  left: 200px;
}
h3{
  display: inline-block;
}
p{
  display: inline-block;
}

</style>

app/views/studios/_form.html.erb
<div class="container-fluid" id="container-id">
  <%= simple_form_for @studio do |f| %>

    <div class="row">
      <div class='col-sm-8'>
        <%= f.input :name %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class='col-sm-8'>
        <%= f.input :location %>
      </div>
    </div>
    <br>
    <div class="row">
      <div class='col-sm-8'>
        <label for="opening_time">
          <abbr title="required">*</abbr>
          Opening Time
        </label>
      </div>
    </div>

    <div class="row">
      <div class='col-sm-8'>
        <%= f.time_select :opening_time ,{ampm: true}%>
      </div>
    </div>
    <br>
    <div class="row">
      <div class='col-sm-8'>
        <label for="closing_time">
          <abbr title="required">*</abbr>
          Closing Time
        </label>
      </div>
    </div>


    <div class="row">
      <div class='col-sm-8'>
        <%= f.time_select :closing_time,{ampm: true} %>
      </div>
    </div>
    <br>

    <div class="row">
      <div class='col-sm-8'>
        <%= f.input :studio_type %>
      </div>
    </div>
    <br>

    <div class="row">
      <div class='col-sm-8'>
        <%= f.input :price %>
      </div>
    </div>

    <div class="row">
      <div class='col-sm-8'>
        <%= f.button :submit ,class: "btn btn-success" %>
      </div>
    </div>

  <% end %>
</div>


<style>
#container-id{
  margin-left: 400px;
}
</style>

app/views/studios/index.html.erb
<div class="container" id="container-id">
  <div class="row">
    <h3><%=@studio.name%><h3>
  </div>
  <div class="row">
    <p><%=@studio.studio_type%></p>
  </div>
  <div class="row">
    <h6> Rs. <%=@studio.price%>/hour<h6>
  </div>
  <div class="row">
    <p>Opens At: <%=@studio.opening_time.strftime("%I:%M %p")%></p>
  </div>
  <div class="row">
    <p>Closes At: <%=@studio.closing_time.strftime("%I:%M %p")%></p>
  </div>
  <div class="row">
    <%= button_to "Book",new_studio_booking_path(@studio),class: "btn btn-success",id: "button-id",method: :get%>
  </div>
</div>


<style>
#container-id{
  margin-left:500px;
}
#button-id{
  margin-right: 1100px;
}

</style>

app/views/studios/new.html.erb
<h1>Create A New Studio<h1>
<%= render "studios/form"%>

app/views/studios/show.html.erb
<% if flash[:notice] %>
   <div class="notice"><%= flash[:notice] %></div>
 <% end %>

<%=button_to "Back",music_studio_index_path,method: :get%>